name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # setup python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # install deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff black

      # run tests
      - name: Run pytest
        run: pytest -q

      # lint with ruff
      - name: Ruff lint
        run: ruff check .

      # check formatting with black
      - name: Black formatting
        run: black --check .
