name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ~/mlops/mlops_pipeline || { mkdir -p ~/mlops && cd ~/mlops && git clone https://github.com/chandanmut/mlops_pipeline.git && cd mlops_pipeline; }
            git fetch --all
            git reset --hard origin/main
            cp .env.example .env || true
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
            echo "S3_RAW_BUCKET=${{ secrets.S3_RAW_BUCKET }}" >> .env
            echo "MLFLOW_ARTIFACTS_BUCKET=${{ secrets.MLFLOW_ARTIFACTS_BUCKET }}" >> .env
            docker compose up -d --build
            docker ps
